#!/bin/bash

# CV Analyzer - Environment File Template Generator (Bash version)
# This script creates a .env file template with placeholder values

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Output functions
print_success() { echo -e "${GREEN}$1${NC}"; }
print_error() { echo -e "${RED}$1${NC}"; }
print_warning() { echo -e "${YELLOW}$1${NC}"; }
print_info() { echo -e "${BLUE}$1${NC}"; }

# Default values
OUTPUT_FILE=".env"
FORCE=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -o|--output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        -f|--force)
            FORCE=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo "Options:"
            echo "  -o, --output FILE    Output file path (default: .env)"
            echo "  -f, --force         Force overwrite existing file"
            echo "  -h, --help          Show this help message"
            exit 0
            ;;
        *)
            print_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Check if file exists and handle overwrite
if [[ -f "$OUTPUT_FILE" && "$FORCE" == "false" ]]; then
    echo -n "File '$OUTPUT_FILE' already exists. Overwrite? (y/N): "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        print_info "Operation cancelled."
        exit 0
    fi
fi

# Create .env template
create_env_template() {
    cat > "$OUTPUT_FILE" << 'EOF'
# CV Analyzer Environment Configuration
# Generated by create-env-template.sh
# 
# This file contains environment variables for the CV Analyzer application.
# Replace placeholder values with your actual secrets.
# 
# IMPORTANT: Never commit this file to version control!
# Make sure .env is in your .gitignore file.

# ==============================================================================
# Database Configuration
# ==============================================================================
DB_PASSWORD=your-secure-database-password-here

# ==============================================================================
# LLM Provider Configuration
# ==============================================================================
# Supported values: OpenAI, Gemini
LLM_PROVIDER=OpenAI

# ==============================================================================
# OpenAI Configuration
# ==============================================================================
# Get your API key from: https://platform.openai.com/api-keys
OPENAI_API_KEY=sk-your-openai-api-key-here
OPENAI_MODEL=gpt-4o-mini

# ==============================================================================
# Google Gemini Configuration
# ==============================================================================
# Get your API key from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY=your-gemini-api-key-here
GEMINI_MODEL=gemini-1.5-flash

# ==============================================================================
# Additional Configuration (if needed)
# ==============================================================================
# Add any additional environment variables here
EOF
}

# Check and update .gitignore
check_gitignore() {
    if [[ -f ".gitignore" ]]; then
        if grep -q "\.env" .gitignore; then
            return 0
        fi
    fi
    return 1
}

add_to_gitignore() {
    if [[ ! -f ".gitignore" ]]; then
        print_info "Creating .gitignore file..."
        cat > .gitignore << 'EOF'
# Environment files
.env
.env.*
EOF
    else
        print_info "Adding .env to existing .gitignore..."
        cat >> .gitignore << 'EOF'

# Environment files
.env
.env.*
EOF
    fi
}

# Main execution
main() {
    print_info "CV Analyzer - Environment File Template Generator"
    print_info "================================================="
    
    # Create .env template
    if create_env_template; then
        print_success "Environment template created: $OUTPUT_FILE"
        
        # Check .gitignore
        if ! check_gitignore; then
            echo -n "Add .env to .gitignore to prevent committing secrets? (Y/n): "
            read -r response
            if [[ ! "$response" =~ ^[Nn]$ ]]; then
                add_to_gitignore
                print_success ".env added to .gitignore"
            fi
        else
            print_success ".env is already in .gitignore"
        fi
        
        print_info ""
        print_info "Next steps:"
        print_info "1. Edit '$OUTPUT_FILE' and replace placeholder values with your actual secrets:"
        print_info "   - Get OpenAI API key from: https://platform.openai.com/api-keys"
        print_info "   - Get Gemini API key from: https://makersuite.google.com/app/apikey"
        print_info "   - Set a secure database password"
        print_info "2. Choose your LLM provider (OpenAI or Gemini)"
        print_info "3. Test your application with: docker-compose up -d"
        print_info ""
        print_warning "IMPORTANT: Never commit '$OUTPUT_FILE' to version control!"
    else
        print_error "Failed to create environment file"
        exit 1
    fi
}

# Run main function
main